Add "up" command

diff --git a/pluginmgnt b/pluginmgnt
--- a/pluginmgnt
+++ b/pluginmgnt
@@ -9,6 +9,7 @@ cmd_usage(){
     echo "Usage: ${basename} <command> [options]"
     echo "Available commands:"
     echo "    list    List all plugins and symlinks in your resource and server folder"
+    echo "    up      Enable a plugin"
     echo ""
     echo "For help on any individual command run \"$ ${basename} -h|--help\""
     echo ""
@@ -23,12 +24,41 @@ cmd_list(){
 
     if [[ ${1} == "resources" ]]; then
         ls -al ${resourcepath} | tail -n +4 | awk '{ print $9" "$10" "$11 }'
+        exit 0
     elif [[ ${1} == "server" ]]; then
         ls -alp ${pluginpath} | grep -v '/$' | tail -n +4 | awk '{ print $9" "$10" "$11 }'
+        exit 0
     else
         echo "Error: only \"server\" and \"resources\" are valid arguments!"
         exit 1
     fi
+}
+
+cmd_up(){
+    if [ "${#}" -ne 1 ]; then
+    then
+        echo "Error: No argument given!"
+        echo "Usage: $ ${basename} up PluginName-latest.jar"
+        exit 1
+    fi
+
+    if [ ! -L "${resourcepath}/${1}" ]; then
+        echo "Error: Couldn't find plugin symlink \"${resourcepath}/${1}\""
+        exit 1
+    fi
+
+    if [ -f "${pluginpath}/${1}" ]; then
+        echo "Info: \"${pluginpath}/${1}\" already exists."
+        MD51=`md5sum ${resourcepath}/${1} | awk '{ print $1 }'`
+        MD52=`md5sum ${pluginpath}/${1} | awk '{ print $1 }'`
+        if [[ "${MD51}" == "${MD52}" ]]; then
+            echo "Error: Checksum of \"${pluginpath}/${1}\" and \"${resourcepath}/${1}\" are the same. Abbort."
+            exit 1
+        fi
+    fi
+
+    ln -sf "${resourcepath}/${1}" "${pluginpath}/${1}"
+    exit 0
 }
   
 cmd=${1}
